/**
 * next-sitemap runs after `next build` (see `postbuild` in package.json).
 *
 * Canonical URL list (services, neighborhood tri-trade hubs, all neighborhood × service pages from `data/neighborhoods.ts`,
 * locations, blog, best-of, static pages) lives in `buildSitemapEntries()` → `lib/sitemap-entries.ts`.
 *
 * Production `/sitemap.xml` is a Next rewrite to `/api/sitemap-xml`, which renders that list.
 * Files here are written only under `.indexnow-tmp/` so we never overwrite the live sitemap route.
 * `scripts/submit-indexnow.ts` submits the same URLs via `buildSitemapEntries()` directly.
 *
 * Live `/robots.txt` is generated by `app/robots.ts` (allow all + production sitemap URL — includes neighborhood hubs).
 * `generateRobotsTxt` below mirrors that for the optional `.indexnow-tmp/robots.txt` artifact.
 *
 * @type {import('next-sitemap').IConfig}
 */
const siteUrl = (process.env.SITE_URL || "https://www.georgetownhomeservices.com").replace(/\/$/, "");

module.exports = {
  siteUrl,
  outDir: ".indexnow-tmp",
  generateRobotsTxt: true,
  generateIndexSitemap: false,
  autoLastmod: false,
  changefreq: "weekly",
  priority: 0.7,
  robotsTxtOptions: {
    policies: [{ userAgent: "*", allow: "/" }],
    /** Public sitemap (dynamic route), not the temp XML files in this folder */
    additionalSitemaps: [`${siteUrl}/sitemap.xml`],
  },
};
