/** Static PDF committed under public/downloads — generated by `npm run generate:pdfs`. */
export const HVAC_TEXAS_HEAT_GUIDE_FILENAME = "hvac-texas-heat-guide.pdf";

export const HVAC_TEXAS_HEAT_GUIDE_PDF_PATH = `/downloads/${HVAC_TEXAS_HEAT_GUIDE_FILENAME}`;
